# system installation and setup details
biblio_web_service_user: "bibweb"
biblio_base_dir_path: "/srv/biblio_web"
biblio_web_venv_path: "{{ biblio_base_dir_path }}/virtualenv"
biblio_web_env_file: "/etc/biblio_web/biblio_service.env"
biblio_web_dir_path: "{{ biblio_base_dir_path }}/biblio_web"
biblio_archive_dir_path: ""

# Biblio library details
biblio_db_path: ""
biblio_dir_path: ""

# Django App env vars
biblio_web_secret_key: ""


# Init script details
## Gunicorn webserver configuration details
gunicorn_pid_path: "/var/run/gunicorn/prod.pid"
gunicorn_error_log: "/var/log/gunicorn/error.log"
gunicorn_access_log: "/var/log/gunicorn/access.log"
gunicorn_ip: "0.0.0.0"
gunicorn_socket: "8000"
gunicorn_config_path: "/etc/biblio_web/gunicorn.prod.py"
## init capabilities and permissions
biblio_web_sec_protect_home: true
biblio_web_sec_protect_system: true
biblio_web_sec_private_devices: true
biblio_web_sec_private_tmp: true
biblio_web_systemd_capabilities: "CAP_NET_BIND_SERVICE"
